apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: chat-based-routing-webpage-be
spec:
  selector:
    matchLabels:
      app: chat-based-routing-webpage-be
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-based-routing-webpage-be
    spec:
      containers:
        - image: 191518685251.dkr.ecr.us-west-1.amazonaws.com/chat-based-routing-webpage-be:latest
          imagePullPolicy: Always
          name: chat-based-routing-webpage-be
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: chat-based-routing-webpage-be-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app: chat-based-routing-webpage-be
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: chat-based-routing-webpage-be-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-1:191518685251:certificate/6eacda8a-0896-4965-930a-ef8bc55cd7c3
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: chat-based-routing-webpage-be-service
                port:
                  number: 80
